--ROLLBACK;
--COMMIT;
BEGIN TRANSACTION; 
ALTER TABLE newdept ADD CONSTRAINT NEWDEPT_PK PRIMARY KEY (deptno);
ALTER TABLE newemp ADD CONSTRAINT NEWEMP_NEWDEPT_FK FOREIGN KEY (deptno) REFERENCES newdept (deptno);
COMMIT;
SELECT * FROM newemp;